modules:
  tcp_connect:
    prober: tcp
    timeout: 5s
  icmp_ping:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
  http_2xx_insecure:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"
